[project]
name = "super-agent-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.9.3",
    "loguru>=0.7.3",
    "mcp>=1.25.0",
    "openai>=2.14.0",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]
